name: Gradle build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install local sql-core
      run: |
        export OLDPWD="${PWD}"
        mkdir -vp /opt && cd /opt
        git clone https://github.com/lensesio/sql-core.git
        cd /opt/sql-core
        git checkout update/scala_12
        ./gradlew clean build install
        cd "${OLDPWD}"
    - name: Install local json-sql
      run: |
        export OLDPWD="${PWD}"
        cd /opt
        git clone https://github.com/lensesio/json-sql.git
        cd /opt/json-sql
        git checkout update/scala_2_12
        ./gradlew clean build install
        cd "${OLDPWD}"
    - name: Download gradle
      run: ./gradlew --version
    - name: Run tests
      run: ./gradlew test
    - name: Run compile
      run: ./gradlew compile
    - name: Run build
      run: ./gradlew build

